### ISSUE TITLE
Does this lib catches only GET requests? 

### ISSUE THREAD

**Issue by arthemium** [BeataKr/axios-har-tracker#6]
I've tried to implement the lib, however I was not able to generate any pages. It does output an empty json file:
```{"log":{"version":"1.2","creator":{"name":"axios-har-tracker","version":"0.1.0"},"pages":[],"entries":[]}}```

I've done everything by the instructions and I'm passing the `axios` object at the begging, however it fails to capture anything.

**Comment by BeataKr** [comment]
Pack traces move from all type of calls. Did you manage to resolve your problem?
